name: CI
on:
    push:
        branches:
            - development
concurrency:
    group: cloud-canvas
jobs:
    CI:
        runs-on: ubuntu-latest
        env:
            TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
            TURBO_TEAM: ${{ vars.TURBO_TEAM }}
        steps:
            - uses: actions/checkout@v4

            - uses: dorny/paths-filter@v3
              id: changes
              with:
                  base: ${{ github.repository_default_branch }}
                  filters: |
                      front:
                        - './apps/client/**'
                        - './packages/terraform/**'
                        - './packages/cloud-graph/**'
                      front-hub:
                        - './apps/hub/**'
                      back:
                        - './apps/server/**'
                        - './packages/ncloud-sdk/**'
                        - './packages/terraform/**'

            - name: Install pnpm
              uses: pnpm/action-setup@v4
              with:
                  version: 9.12.3
            - name: Use Node.js 20
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: 'pnpm'
            - name: Install dependencies
              run: pnpm install

            - name: Install turbo
              run: npm install -g turbo

            - name: Build applications
              run: pnpm turbo build

            - name: NCP registry login
              uses: docker/login-action@v3
              with:
                  registry: ${{ secrets.NCP_REGISTRY }}
                  username: ${{ secrets.NCP_ACCESS_KEY }}
                  password: ${{ secrets.NCP_SECRET_KEY }}

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Docker front image build and push
              if: steps.changes.outputs.front == 'true'
              uses: docker/build-push-action@v6
              with:
                  context: .
                  file: ./apps/client/Dockerfile.CI
                  push: true
                  tags: |
                      cloud-canvas.kr.ncr.ntruss.com/front:dev
                      cloud-canvas.kr.ncr.ntruss.com/front:${{ github.sha }}
                  cache-from: type=registry,ref=cloud-canvas.kr.ncr.ntruss.com/front:buildcache
                  cache-to: type=registry,ref=cloud-canvas.kr.ncr.ntruss.com/front:buildcache,mode=max

            - name: Docker front-hub image build and push
              if: steps.changes.outputs.front-hub == 'true'
              uses: docker/build-push-action@v6
              with:
                  context: .
                  file: ./apps/hub/Dockerfile.CI
                  push: true
                  tags: |
                      cloud-canvas.kr.ncr.ntruss.com/front-hub:dev
                      cloud-canvas.kr.ncr.ntruss.com/front-hub:${{ github.sha }}
                  cache-from: type=registry,ref=cloud-canvas.kr.ncr.ntruss.com/front-hub:buildcache
                  cache-to: type=registry,ref=cloud-canvas.kr.ncr.ntruss.com/front-hub:buildcache,mode=max

            - name: Docker back image build and push
              if: steps.changes.outputs.back == 'true'
              uses: docker/build-push-action@v6
              with:
                  context: .
                  file: ./apps/server/Dockerfile.CI
                  push: true
                  tags: |
                      cloud-canvas.kr.ncr.ntruss.com/back:dev
                      cloud-canvas.kr.ncr.ntruss.com/back:${{ github.sha }}
                  cache-from: type=registry,ref=cloud-canvas.kr.ncr.ntruss.com/back:buildcache
                  cache-to: type=registry,ref=cloud-canvas.kr.ncr.ntruss.com/back:buildcache,mode=max

    # CD:
    #     needs: CI
    #     runs-on: ubuntu-latest

    #     steps:
    #         - name: Add SSH known hosts
    #           run: |
    #               mkdir -p ~/.ssh
    #               ssh-keyscan -p ${{ secrets.NCP_DEV_INSTANCE_PORT }} ${{ secrets.NCP_DEV_INSTANCE }} >> ~/.ssh/known_hosts
    #         - name: SSH login and deploy
    #           run: |
    #               printf "%s" "${{ secrets.NCP_DEV_SSH }}" > dev_login.pem
    #               chmod 600 dev_login.pem
    #               ssh -t -i dev_login.pem ncloud@${{ secrets.NCP_DEV_INSTANCE }} -p ${{ secrets.NCP_DEV_INSTANCE_PORT }} './docker.sh'
