name: PR-BUILD-TEST

on:
    pull_request:
        branches:
            - development
        types:
            - opened
            - reopened
            - synchronize
            - ready_for_review

jobs:
    build-test:
        runs-on: ubuntu-latest
        env:
            TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
            TURBO_TEAM: ${{ vars.TURBO_TEAM }}
        steps:
            - uses: actions/checkout@v4
            - name: Install pnpm
              uses: pnpm/action-setup@v4
              with:
                  version: 9.12.3
            - name: Use Node.js 20
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: 'pnpm'
            - name: Install dependencies
              run: pnpm install

            - name: Install turbo
              run: npm install -g turbo

            - name: Build applications
              run: pnpm turbo build
